services:
  api:
    build: ./backend
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  frontend:
    build: ./frontend
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  qdrant_storage:
